### ISSUE TITLE
Why exclude `no-undef` rules?

### ISSUE THREAD

**Issue by vannizer** [jitta/eslint-config-jitta#2]
IMO I do really think this one pretty useful, I didn't get the idea to exclude this rule?

**Comment by groupdoll** [comment]
เราเอา rule มาจาก repo หลายๆอันใน github/jitta อะ
เห็นด้วยว่าไม่ควร disable rule นี้

**Comment by vannizer** [comment]
I've made PR to excludes this rule. https://github.com/jitta/eslint-config-jitta/pull/3
