### ISSUE TITLE
Should we disable `no-plusplus` rule?

### ISSUE THREAD

**Issue by vannizer** [jitta/eslint-config-jitta#6]
I reckon it's annoying every time I've to use **for loop** like,
```js
for (let i = 0; i<arr.length; i++) {...}
```
and there's an error from this [no-plusplus](http://eslint.org/docs/rules/no-plusplus) rule
so, I need to write this instead
```js
for (let i = 0; i<arr.length; i += 1) {...}
```
which I feels a bit strange to write it like this.

What do you think about?

**Comment by nuttt** [comment]
For me, I prefer `+= 1` than `++` because I mostly use it in a statement for than a loop so,
```javascript
idx +=1
```
is look nicer than
```javascript
idx++
```

for for-loop, I mostly use `forEach` and `map`

**Comment by vannizer** [comment]
@nuttt  I got the point about `+=1` and `++`

but, about `forEach` and `map`, I reckon two of these couldn't replace `for-loop` for all cases 
**e.g.,** You wanna loop **until** it **matches some conditions** then stop.

**Comment by groupdoll** [comment]
I think
```js
idx += 1
```
is more flexible, it easy to change 1 with any number e.g.
```js
idx += 47
```
